#!/usr/bin/env python3
"""Generate Terraform resource templates from a Terraform provider schema JSON.

Reads the output of `terraform providers schema -json` and emits one `.tf` per
resource type, following the Grauss pattern documented in
`.cursor/rules/grauss-terraform-templates.mdc`:

  * resource label is always `grauss`
  * `for_each = local.<plural>`
  * required scalars  ->  <arg> = each.value.<arg>
  * optional scalars  ->  <arg> = try(each.value.<arg>, null)
  * nested blocks     ->  dynamic with for_each over JSON list/set/map/object

The shared JSON loader lives in `providers/<cloud>/_locals.tf` and is not
touched by this generator; codegen only writes files that do not begin with `_`.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

GENERATED_BANNER = (
    "# Generated by scripts/codegen.py from the pinned provider schema.\n"
    "# Do not edit by hand; rerun `task generate:<cloud>`.\n"
)

# Skipped at the top level of a resource block. `id` is the implicit resource
# identifier — Terraform's core rejects any assignment even when the schema
# marks it Optional+Computed. The rest are HCL meta-arguments. Inside nested
# `dynamic` content blocks these names are valid attribute names (e.g. a
# CloudFront origin `id`, a step-scaling metric dimension `id`, a CodePipeline
# action `provider`), so we only filter them at the resource top level.
TOP_LEVEL_SKIP = {"id", "count", "for_each", "depends_on", "provider", "lifecycle"}


# Explicit overrides for short names (post-strip-prefix) whose correct plural
# isn't reachable by the general rules below. Add entries here rather than
# patching the algorithm when a new edge case turns up.
_PLURAL_EXCEPTIONS: dict[str, str] = {}


def _plural_word(word: str) -> str:
    """Pluralize a single English word using standard suffix rules."""
    if word.endswith(("s", "x", "z", "ch", "sh")):
        return word + "es"
    if word.endswith("y") and len(word) >= 2 and word[-2] not in "aeiou":
        return word[:-1] + "ies"
    return word + "s"


def naive_plural(name: str) -> str:
    """Return a best-effort plural for a snake_case Terraform resource name.

    Only the last word of the snake_case identifier is pluralised, which
    avoids spurious -es/-ies suffixes caused by intermediate words that happen
    to end in s/x/z/y (e.g. ``kubernetes_cluster`` → ``kubernetes_clusters``,
    not ``kuberneteses_cluster``).

    Examples::

        storage_account          → storage_accounts
        virtual_network          → virtual_networks
        resource_group_policy    → resource_group_policies
        network_security_group   → network_security_groups
        kubernetes_cluster       → kubernetes_clusters
        subnet                   → subnets

    Add known exceptions to ``_PLURAL_EXCEPTIONS`` rather than complicating
    this function.
    """
    if name in _PLURAL_EXCEPTIONS:
        return _PLURAL_EXCEPTIONS[name]
    if "_" in name:
        prefix, _, last = name.rpartition("_")
        return f"{prefix}_{_plural_word(last)}"
    return _plural_word(name)


def is_skippable(attr_schema: dict) -> bool:
    """Computed-only attributes (no required/optional) are output-only."""
    required = attr_schema.get("required", False)
    optional = attr_schema.get("optional", False)
    computed = attr_schema.get("computed", False)
    return computed and not (required or optional)


def render_attribute(name: str, schema: dict, indent: str, iterator: str) -> str:
    if is_skippable(schema):
        return ""
    if schema.get("required"):
        return f"{indent}{name} = {iterator}.value.{name}\n"
    return f"{indent}{name} = try({iterator}.value.{name}, null)\n"


def render_block(block_name: str, block_schema: dict, indent: str, parent_iter: str) -> str:
    nesting = block_schema.get("nesting_mode", "single")
    inner = block_schema.get("block", {}) or {}

    if nesting in ("single", "group"):
        for_each_expr = (
            f"try({parent_iter}.value.{block_name}, null) != null"
            f" ? [{parent_iter}.value.{block_name}] : []"
        )
    elif nesting == "map":
        for_each_expr = f"try(tomap({parent_iter}.value.{block_name}), {{}})"
    else:  # list | set | anything else
        for_each_expr = f"try(tolist({parent_iter}.value.{block_name}), [])"

    inner_iter = block_name
    out: list[str] = []
    out.append(f'{indent}dynamic "{block_name}" {{\n')
    out.append(f"{indent}  for_each = {for_each_expr}\n")
    out.append(f"{indent}  content {{\n")

    attrs = inner.get("attributes", {}) or {}
    required = sorted(
        n for n, s in attrs.items()
        if s.get("required") and not is_skippable(s)
    )
    optional = sorted(
        n for n, s in attrs.items()
        if not s.get("required") and not is_skippable(s)
    )

    for n in required:
        out.append(render_attribute(n, attrs[n], indent + "    ", inner_iter))
    if required and optional:
        out.append("\n")
    for n in optional:
        out.append(render_attribute(n, attrs[n], indent + "    ", inner_iter))

    sub_blocks = inner.get("block_types", {}) or {}
    if sub_blocks and (required or optional):
        out.append("\n")
    for sub_name in sorted(sub_blocks):
        out.append(render_block(sub_name, sub_blocks[sub_name], indent + "    ", inner_iter))

    out.append(f"{indent}  }}\n")
    out.append(f"{indent}}}\n")
    return "".join(out)


def render_resource(resource_name: str, schema: dict, json_key: str, local_var: str) -> str:
    block = schema.get("block", {}) or {}
    attrs = block.get("attributes", {}) or {}
    blocks = block.get("block_types", {}) or {}

    required = sorted(
        n for n, s in attrs.items()
        if s.get("required") and n not in TOP_LEVEL_SKIP and not is_skippable(s)
    )
    optional = sorted(
        n for n, s in attrs.items()
        if not s.get("required") and n not in TOP_LEVEL_SKIP and not is_skippable(s)
    )

    out: list[str] = []
    out.append(GENERATED_BANNER)
    out.append("\n")
    out.append("locals {\n")
    out.append(f"  {local_var} = {{\n")
    out.append(f'    for v in lookup(local.json_data, "{json_key}", []) :\n')
    out.append('    join("-", [for k in ["name"] : try(v[k], "")]) => v\n')
    out.append("  }\n")
    out.append("}\n")
    out.append("\n")
    out.append(f'resource "{resource_name}" "grauss" {{\n')
    out.append(f"  for_each = local.{local_var}\n")
    out.append("\n")

    for n in required:
        out.append(render_attribute(n, attrs[n], "  ", "each"))
    if required and optional:
        out.append("\n")
    for n in optional:
        out.append(render_attribute(n, attrs[n], "  ", "each"))

    if blocks and (required or optional):
        out.append("\n")
    for n in sorted(blocks):
        out.append(render_block(n, blocks[n], "  ", "each"))
        out.append("\n")

    # strip trailing blank lines before the closing brace
    while out and out[-1].strip() == "":
        out.pop()
    out.append("}\n")
    return "".join(out)


def find_provider_key(schema: dict, source: str) -> str | None:
    keys = list((schema.get("provider_schemas") or {}).keys())
    for k in keys:
        # keys look like "registry.terraform.io/hashicorp/aws"
        if k.endswith("/" + source):
            return k
    for k in keys:
        if source in k:
            return k
    return None


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--schema", required=True, help="path to provider schema JSON")
    p.add_argument(
        "--provider-source", required=True,
        help='provider source, e.g. "hashicorp/aws", "hashicorp/azurerm", "oracle/oci"',
    )
    p.add_argument(
        "--prefix", required=True,
        help='resource name prefix, e.g. "aws_", "azurerm_", "azuread_", "google_", "oci_"',
    )
    p.add_argument("--out", required=True, help="output directory (providers/<cloud>/)")
    p.add_argument(
        "--strip-prefix", action="store_true",
        help="strip the provider prefix from the emitted filename",
    )
    p.add_argument(
        "--clean", action="store_true",
        help="remove all non-underscore .tf files in --out before generating",
    )
    p.add_argument(
        "--exclude", default="",
        help="comma-separated list of resource names to skip",
    )
    p.add_argument(
        "--include-deprecated", action="store_true",
        help="generate templates for resources the provider marks as deprecated (skipped by default)",
    )
    args = p.parse_args()

    try:
        schema: dict[str, Any] = json.loads(Path(args.schema).read_text())
    except FileNotFoundError:
        print(f"codegen: schema file not found: {args.schema}", file=sys.stderr)
        return 2

    key = find_provider_key(schema, args.provider_source)
    if not key:
        print(
            f"codegen: provider source '{args.provider_source}' not in schema; "
            f"known: {list((schema.get('provider_schemas') or {}).keys())}",
            file=sys.stderr,
        )
        return 2

    resources = (schema["provider_schemas"][key].get("resource_schemas") or {})
    exclude = {x.strip() for x in args.exclude.split(",") if x.strip()}

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.clean:
        for f in out_dir.glob("*.tf"):
            if f.name.startswith("_"):
                continue
            f.unlink(missing_ok=True)

    written = 0
    skipped_deprecated = 0
    for resource_name in sorted(resources):
        if not resource_name.startswith(args.prefix):
            continue
        if resource_name in exclude:
            continue
        if not args.include_deprecated and resources[resource_name].get("block", {}).get("deprecated"):
            skipped_deprecated += 1
            continue
        short = resource_name[len(args.prefix):] if args.strip_prefix else resource_name
        local_var = naive_plural(short)
        fname = f"{short}.tf"
        content = render_resource(resource_name, resources[resource_name], short, local_var)
        (out_dir / fname).write_text(content)
        written += 1

    deprecated_note = f", skipped {skipped_deprecated} deprecated" if skipped_deprecated else ""
    print(
        f"codegen: wrote {written} resource templates to {out_dir} "
        f"(provider: {args.provider_source}, prefix: {args.prefix}{deprecated_note})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
