#!/usr/bin/env bash
# Generate Terraform resource templates for a cloud from the pinned provider
# schema. Downloads the provider into a cache dir, dumps the schema, and runs
# scripts/codegen.py to write providers/<cloud>/<resource>.tf for every
# resource type the provider exposes at that pinned version.
#
# Usage:
#   bash scripts/generate-resources.sh <cloud>      # cloud = aws|azure|gcp|oci
#
# Reads provider pins from .env / .env.example (ENGINE_AWS_PROVIDER_VERSION etc.) so
# regenerating after a version bump is just: edit pin, rerun.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CLOUD="${1:?usage: generate-resources.sh <aws|azure|gcp|oci|ovh>}"
case "$CLOUD" in aws|azure|gcp|oci|ovh) ;; *)
  echo "generate-resources: cloud must be one of: aws azure gcp oci ovh" >&2
  exit 1
  ;;
esac

if [[ -f "$REPO_ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$REPO_ROOT/.env"
  set +a
fi

# Resolve the IaC binary: honour ENGINE_IAC_ENGINE if set, otherwise
# auto-detect — prefer terraform, fall back to tofu (OpenTofu).
resolve_iac_bin() {
  case "${ENGINE_IAC_ENGINE:-}" in
    terraform)
      command -v terraform >/dev/null 2>&1 || { echo "generate-resources: terraform not found on PATH" >&2; exit 1; }
      echo terraform ;;
    opentofu|tofu)
      command -v tofu >/dev/null 2>&1 || { echo "generate-resources: tofu not found on PATH" >&2; exit 1; }
      echo tofu ;;
    "")
      if   command -v terraform >/dev/null 2>&1; then echo terraform
      elif command -v tofu      >/dev/null 2>&1; then echo tofu
      else
        echo "generate-resources: neither terraform nor tofu found on PATH. Install one or set ENGINE_IAC_ENGINE." >&2
        exit 1
      fi ;;
    *)
      echo "generate-resources: ENGINE_IAC_ENGINE='${ENGINE_IAC_ENGINE}' is not valid. Use terraform, opentofu, or tofu." >&2
      exit 1 ;;
  esac
}

IAC_BIN="$(resolve_iac_bin)"
echo "generate-resources: using $IAC_BIN"

# Defaults match .env.example so the script works on a fresh checkout (ENGINE_* or legacy unprefixed after sourcing .env).
AZURERM_VERSION="${ENGINE_AZURERM_VERSION:-${AZURERM_VERSION:-=4.72.0}}"
AZUREAD_VERSION="${ENGINE_AZUREAD_VERSION:-${AZUREAD_VERSION:-=3.8.0}}"
GOOGLE_PROVIDER_VERSION="${ENGINE_GOOGLE_PROVIDER_VERSION:-${GOOGLE_PROVIDER_VERSION:-=7.32.0}}"
AWS_PROVIDER_VERSION="${ENGINE_AWS_PROVIDER_VERSION:-${AWS_PROVIDER_VERSION:-=6.44.0}}"
OCI_PROVIDER_VERSION="${ENGINE_OCI_PROVIDER_VERSION:-${OCI_PROVIDER_VERSION:-=8.13.0}}"
OVH_PROVIDER_VERSION="${ENGINE_OVH_PROVIDER_VERSION:-${OVH_PROVIDER_VERSION:-=2.13.1}}"

# strip leading "=" from constraint pins for the bare version literal
strip_eq() { printf '%s' "${1#=}"; }

CACHE_ROOT="$REPO_ROOT/tmp/codegen/$CLOUD"
mkdir -p "$CACHE_ROOT"

write_versions_tf() {
  # $1 path, $2 JSON content
  printf '%s' "$2" > "$1/versions.tf.json"
}

# render_framework_files <cloud>
#
# Emits the two non-resource files every generated `.tf` depends on:
#
#   providers/<cloud>/_locals.tf     — `var.project` + the shared `json_data`
#                                      loader keyed by JSON subdirectory name.
#   providers/<cloud>/_<cloud>.tf.json — required_providers + base provider
#                                      config. Version fields keep
#                                      `__*_VERSION__` placeholders that
#                                      `scripts/inject-provider-versions.sh`
#                                      resolves at build/workspace time.
#
# These files are tracked in git alongside the generated resource templates
# because the Docker build copies `providers/<cloud>/` whole; codegen overwrites
# them deterministically on every run.
render_framework_files() {
  local cloud="$1"
  local out_dir="$REPO_ROOT/providers/$cloud"
  mkdir -p "$out_dir"

  cat > "$out_dir/_locals.tf" <<EOF
# Generated by scripts/generate-resources.sh from the pinned provider schema.
# Do not edit by hand; rerun \`task generate:$cloud\`.

variable "project" {
  type        = string
  description = "Name of the project folder under data/$cloud/<project>/ when using repo layouts; unused when workspace/data is a flat copy of that folder."
  default     = "project-01"
}

locals {
  data_project_root = fileexists("\${path.module}/.iac_engine_bin") ? (
    try(length(fileset("\${path.module}/data/$cloud", "**")) >= 0, false) ? "\${path.module}/data/$cloud/\${var.project}" : "\${path.module}/data"
  ) : abspath("\${path.module}/../../data/$cloud/\${var.project}")

  json_files = try(fileset(local.data_project_root, "**/*.json"), [])

  json_directories = distinct([for f in local.json_files : basename(dirname(f))])

  json_data = {
    for dir_name in local.json_directories : dir_name => [
      for f in fileset("\${local.data_project_root}/\${dir_name}", "*.json") :
      jsondecode(file("\${local.data_project_root}/\${dir_name}/\${f}"))
    ]
  }
}
EOF

  case "$cloud" in
    aws)
      cat > "$out_dir/_aws.tf.json" <<'JSON'
{
  "terraform": [
    {
      "required_providers": {
        "aws": {
          "source": "hashicorp/aws",
          "version": "__AWS_PROVIDER_VERSION__"
        }
      }
    },
    {
      "required_version": "__REQUIRED_VERSION__"
    }
  ],
  "provider": [
    {
      "aws": {}
    }
  ]
}
JSON
      ;;
    azure)
      cat > "$out_dir/_azure.tf.json" <<'JSON'
{
  "terraform": [
    {
      "required_providers": {
        "azurerm": {
          "source": "hashicorp/azurerm",
          "version": "__AZURERM_VERSION__"
        },
        "azuread": {
          "source": "hashicorp/azuread",
          "version": "__AZUREAD_VERSION__"
        }
      }
    },
    {
      "required_version": "__REQUIRED_VERSION__"
    }
  ],
  "provider": [
    {
      "azurerm": {
        "features": {
          "key_vault": {
            "purge_soft_delete_on_destroy": true
          }
        },
        "storage_use_azuread": true
      }
    },
    {
      "azuread": {}
    }
  ]
}
JSON
      ;;
    gcp)
      cat > "$out_dir/_gcp.tf.json" <<'JSON'
{
  "terraform": [
    {
      "required_providers": {
        "google": {
          "source": "hashicorp/google",
          "version": "__GOOGLE_PROVIDER_VERSION__"
        }
      }
    },
    {
      "required_version": "__REQUIRED_VERSION__"
    }
  ],
  "provider": [
    {
      "google": {}
    }
  ]
}
JSON
      ;;
    oci)
      cat > "$out_dir/_oci.tf.json" <<'JSON'
{
  "terraform": [
    {
      "required_providers": {
        "oci": {
          "source": "oracle/oci",
          "version": "__OCI_PROVIDER_VERSION__"
        }
      }
    },
    {
      "required_version": "__REQUIRED_VERSION__"
    }
  ],
  "provider": [
    {
      "oci": {}
    }
  ]
}
JSON
      ;;
    ovh)
      # OVH _locals.tf: overwrites the common template. Uses a two-locals pattern so
      # var.ovh_service_name is injected into every resource instance that omits the
      # service_name field — JSON value wins when present (merge uses last-wins order).
      cat > "$out_dir/_locals.tf" <<EOF
# Generated by scripts/generate-resources.sh from the pinned provider schema.
# Do not edit by hand; rerun \`task generate:ovh\`.

variable "project" {
  type        = string
  description = "Name of the project folder under data/ovh/<project>/ when using repo layouts; unused when workspace/data is a flat copy of that folder."
  default     = "project-01"
}

variable "ovh_service_name" {
  type        = string
  description = "OVH Cloud project ID (UUID shown in OVH Control Panel → Public Cloud → Settings). Passed as TF_VAR_ovh_service_name."
  default     = ""
}

variable "ovh_s3_region" {
  type        = string
  description = "OVH S3-compatible Object Storage region slug (e.g. gra, sbg, de, uk)."
  default     = "gra"
}

variable "ovh_s3_endpoint" {
  type        = string
  description = "OVH S3-compatible Object Storage endpoint URL."
  default     = "https://s3.gra.io.cloud.ovh.net"
}

variable "ovh_s3_access_key" {
  type        = string
  description = "OVH S3-compatible Object Storage access key (from ovh_cloud_project_user_s3_credential)."
  default     = ""
}

variable "ovh_s3_secret_key" {
  type        = string
  description = "OVH S3-compatible Object Storage secret key (from ovh_cloud_project_user_s3_credential)."
  default     = ""
  sensitive   = true
}

locals {
  data_project_root = fileexists("\${path.module}/.iac_engine_bin") ? (
    try(length(fileset("\${path.module}/data/ovh", "**")) >= 0, false) ? "\${path.module}/data/ovh/\${var.project}" : "\${path.module}/data"
  ) : abspath("\${path.module}/../../data/ovh/\${var.project}")

  json_files = try(fileset(local.data_project_root, "**/*.json"), [])

  json_directories = distinct([for f in local.json_files : basename(dirname(f))])

  _json_data_raw = {
    for dir_name in local.json_directories : dir_name => [
      for f in fileset("\${local.data_project_root}/\${dir_name}", "*.json") :
      jsondecode(file("\${local.data_project_root}/\${dir_name}/\${f}"))
    ]
  }
}

# Inject var.ovh_service_name into every resource instance that does not set it
# explicitly in JSON. The JSON value wins when present (merge uses last-wins order).
locals {
  json_data = {
    for resource_type, instances in local._json_data_raw :
    resource_type => [
      for v in instances :
      merge({ service_name = var.ovh_service_name }, v)
    ]
  }
}
EOF

      # _ovh.tf.json: bundles ovh/ovh + hashicorp/aws (S3-compatible Object Storage for state backend).
      # The aws provider is configured for OVH's S3 endpoint; credentials come from TF_VAR_*.
      cat > "$out_dir/_ovh.tf.json" <<'JSON'
{
  "terraform": [
    {
      "required_providers": {
        "ovh": {
          "source": "ovh/ovh",
          "version": "__OVH_PROVIDER_VERSION__"
        },
        "aws": {
          "source": "hashicorp/aws",
          "version": "__AWS_PROVIDER_VERSION__"
        }
      }
    },
    {
      "required_version": "__REQUIRED_VERSION__"
    }
  ],
  "provider": [
    {
      "ovh": {}
    },
    {
      "aws": {
        "region": "${var.ovh_s3_region}",
        "access_key": "${var.ovh_s3_access_key}",
        "secret_key": "${var.ovh_s3_secret_key}",
        "endpoints": [
          {
            "s3": "${var.ovh_s3_endpoint}"
          }
        ],
        "skip_credentials_validation": true,
        "skip_region_validation": true,
        "skip_requesting_account_id": true,
        "skip_s3_checksum": true,
        "skip_metadata_api_check": true
      }
    }
  ]
}
JSON

      # _s3_bucket.tf: framework file for OVH Object Storage state buckets.
      # Prefix _ preserves it from codegen --clean. Uses the aws provider configured above.
      cat > "$out_dir/_s3_bucket.tf" <<'HCL'
# Framework file — OVH Object Storage bucket via S3-compatible API.
# Generated by scripts/generate-resources.sh. Do not edit by hand; rerun `task generate:ovh`.
# Provider: hashicorp/aws configured for OVH S3 endpoint (see _ovh.tf.json).
# Data path: data/ovh/<project>/s3_bucket/<name>.json

locals {
  s3_buckets = {
    for v in lookup(local.json_data, "s3_bucket", []) :
    try(v["bucket"], v["name"], "") => v
  }
}

resource "aws_s3_bucket" "grauss" {
  for_each = local.s3_buckets

  bucket        = each.value.bucket
  force_destroy = try(each.value.force_destroy, false)

  tags = try(each.value.tags, null)
}
HCL
      ;;
  esac
}

# Build per-cloud versions.tf.json — one provider per cloud, except Azure which
# bundles azurerm + azuread (single image, single init).
case "$CLOUD" in
  aws)
    VERSIONS_JSON=$(cat <<JSON
{
  "terraform": [
    {
      "required_providers": {
        "aws": { "source": "hashicorp/aws", "version": "$AWS_PROVIDER_VERSION" }
      }
    }
  ]
}
JSON
)
    ;;
  azure)
    VERSIONS_JSON=$(cat <<JSON
{
  "terraform": [
    {
      "required_providers": {
        "azurerm": { "source": "hashicorp/azurerm", "version": "$AZURERM_VERSION" },
        "azuread": { "source": "hashicorp/azuread", "version": "$AZUREAD_VERSION" }
      }
    }
  ]
}
JSON
)
    ;;
  gcp)
    VERSIONS_JSON=$(cat <<JSON
{
  "terraform": [
    {
      "required_providers": {
        "google": { "source": "hashicorp/google", "version": "$GOOGLE_PROVIDER_VERSION" }
      }
    }
  ]
}
JSON
)
    ;;
  oci)
    VERSIONS_JSON=$(cat <<JSON
{
  "terraform": [
    {
      "required_providers": {
        "oci": { "source": "oracle/oci", "version": "$OCI_PROVIDER_VERSION" }
      }
    }
  ]
}
JSON
)
    ;;
  ovh)
    # OVH bundles ovh/ovh + hashicorp/aws (for S3-compatible Object Storage state backend).
    VERSIONS_JSON=$(cat <<JSON
{
  "terraform": [
    {
      "required_providers": {
        "ovh": { "source": "ovh/ovh", "version": "$OVH_PROVIDER_VERSION" },
        "aws": { "source": "hashicorp/aws", "version": "$AWS_PROVIDER_VERSION" }
      }
    }
  ]
}
JSON
)
    ;;
esac

write_versions_tf "$CACHE_ROOT" "$VERSIONS_JSON"

# init only if .terraform is missing or lock is older than versions.tf.json
SCHEMA_FILE="$CACHE_ROOT/schema.json"
NEED_INIT=1
if [[ -d "$CACHE_ROOT/.terraform" && -f "$CACHE_ROOT/.terraform.lock.hcl" && -f "$SCHEMA_FILE" ]]; then
  if [[ "$CACHE_ROOT/.terraform.lock.hcl" -nt "$CACHE_ROOT/versions.tf.json" ]]; then
    NEED_INIT=0
  fi
fi

if [[ $NEED_INIT -eq 1 ]]; then
  echo "generate-resources: initializing provider in $CACHE_ROOT"
  ( cd "$CACHE_ROOT" && "$IAC_BIN" init -input=false -upgrade >/dev/null )
  echo "generate-resources: dumping provider schema"
  ( cd "$CACHE_ROOT" && "$IAC_BIN" providers schema -json > schema.json )
fi

OUT_DIR="$REPO_ROOT/providers/$CLOUD"
mkdir -p "$OUT_DIR"

# Emit the non-resource framework files (_locals.tf, _<cloud>.tf.json) every
# generated `.tf` depends on. Idempotent; rerun overwrites with the same
# content unless the templates change.
render_framework_files "$CLOUD"

# Per-cloud exclude file: scripts/codegen-overrides/<cloud>.exclude.txt
# One resource type per line, blank lines and `#` comments ignored. Read into
# a comma-separated string for --exclude.
EXCLUDE_FILE="$SCRIPT_DIR/codegen-overrides/$CLOUD.exclude.txt"
EXCLUDE_LIST=""
if [[ -f "$EXCLUDE_FILE" ]]; then
  # grep exits 1 when an exclude file is comment-only (gcp/oci today). `|| true`
  # keeps `set -e` from aborting the whole run on that empty match.
  EXCLUDE_LIST="$(grep -Ev '^\s*(#|$)' "$EXCLUDE_FILE" | paste -sd, - || true)"
fi

run_codegen() {
  # $1 provider-source, $2 prefix, $3 extra args (e.g. --clean)
  python3 "$SCRIPT_DIR/codegen.py" \
    --schema "$SCHEMA_FILE" \
    --provider-source "$1" \
    --prefix "$2" \
    --out "$OUT_DIR" \
    --strip-prefix \
    --exclude "$EXCLUDE_LIST" \
    $3
}

case "$CLOUD" in
  aws)
    run_codegen "hashicorp/aws" "aws_" "--clean"
    ;;
  azure)
    # azurerm first with --clean to wipe the prior generation; azuread runs
    # without --clean so it doesn't wipe azurerm's output. azuread emits
    # with its prefix preserved (no --strip-prefix) so files cannot collide
    # with azurerm short names (e.g. azurerm_user -> user.tf vs
    # azuread_user -> azuread_user.tf).
    run_codegen "hashicorp/azurerm" "azurerm_" "--clean"
    python3 "$SCRIPT_DIR/codegen.py" \
      --schema "$SCHEMA_FILE" \
      --provider-source "hashicorp/azuread" \
      --prefix "azuread_" \
      --out "$OUT_DIR" \
      --exclude "$EXCLUDE_LIST"
    ;;
  gcp)
    run_codegen "hashicorp/google" "google_" "--clean"
    ;;
  oci)
    run_codegen "oracle/oci" "oci_" "--clean"
    ;;
  ovh)
    run_codegen "ovh/ovh" "ovh_" "--clean"
    ;;
esac

echo "generate-resources: $IAC_BIN fmt -recursive $OUT_DIR"
"$IAC_BIN" fmt -recursive "$OUT_DIR" >/dev/null || true

echo "generate-resources: done for $CLOUD"
